version: "3.6"

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            args:
                - TZ=Asia/Taipei
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ../www:/var/www/html
            - ../logs/nginx:/var/log/nginx
        depends_on:
            - php-fpm
        networks:
            - backend

    php-fpm:
        container_name: php-fpm
        build:
            context: ./php-fpm
            args:
                - TZ=Asia/Taipei
                - PHP_TIMEZONE=Asia/Taipei
        volumes:
            - ./php-fpm/php72.ini:/usr/local/etc/php/php.ini
            - ../www:/var/www/html
        expose:
            - 9000
        networks:
            - backend

    mysql:
        container_name: mysql
        build:
            context: ./mysql
            args:
                - TZ=Asia/Taipei
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ../data/mysql:/var/lib/mysql
        networks:
            - backend

    redis:
        container_name: redis
        build:
            context: ./redis
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    backend:
        driver: bridge
