version: "3.6"

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            args:
                - TZ=UTC
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ../www:/var/www/html
            - ../logs/nginx:/var/log/nginx
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
        depends_on:
            - php-fpm
        networks:
            backend:
                aliases:
                    - infyom.test
                    - wordpress.test

    php-fpm:
        container_name: php-fpm
        build:
            context: ./php-fpm
        volumes:
            - ../www:/var/www/html
        expose:
            - 9000
        networks:
            - backend

    mysql:
        container_name: mysql
        build:
            context: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ../data/mysql:/var/lib/mysql
        networks:
            - backend

    postgresql:
        container_name: postgresql
        build:
            context: ./postgresql
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - ../data/postgresql:/var/lib/postgresql
        networks:
            - backend

    redis:
        container_name: redis
        build:
            context: ./redis
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    backend:
        driver: bridge
